version: 2

updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: weekly
    assignees:
      - janm-dev
    labels:
      - updates
    groups:
      minor:
        update-types:
          - "minor"
          - "patch"
