targets = [
	{ triple = "x86_64-unknown-linux-gnu" },
	{ triple = "x86_64-unknown-linux-musl" },
	{ triple = "x86_64-pc-windows-msvc" },
	{ triple = "aarch64-unknown-linux-gnu" },
]

[advisories]
vulnerability = "deny"
unmaintained = "deny"
yanked = "deny"
notice = "warn"
ignore = []

[licenses]
unlicensed = "deny"
copyleft = "deny"
confidence-threshold = 0.8
allow = [
	"Unlicense",        # https://spdx.org/licenses/Unlicense
	"CC0-1.0",          # https://spdx.org/licenses/CC0-1.0
	"MIT",              # https://spdx.org/licenses/MIT
	"BSD-3-Clause",     # https://spdx.org/licenses/BSD-3-Clause
	"Zlib",             # https://spdx.org/licenses/Zlib
	"Apache-2.0",       # https://spdx.org/licenses/Apache-2.0
	"Unicode-DFS-2016", # https://spdx.org/licenses/Unicode-DFS-2016
]
exceptions = [
	{ name = "final-countdown", allow = [
		"AGPL-3.0",
	] },
]
default = "deny"

[licenses.private]
ignore = false

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [
	"https://github.com/rust-lang/crates.io-index",
]
allow-git = []
